{
    'name': 'is_sale_10',
    'version': '2.0',
    'author': 'Intellisoft',
    'website':'http://www.intellisoft.sd',
    'sequence': 4,
    'category': 'Sale',
    'description':"A module that manages customers sales (Odoo 10).",

    'depends': ['sale','is_stock_10','check_followups','is_purchase_10'],
    'data': [
        'security/ir.model.access.csv',
        # 'security/sales_security.xml',
        'views/is_sale_view.xml',
        'views/valution_view.xml',
        'views/boun_sequence.xml',
        'report/quation_tamplate_view.xml',
        'report/external_quation_tamplate_view.xml',
        'report/report.xml',
        'report/sales_report_view.xml',
        'wizard/sales_report_wizard_view.xml',
        'report/sales_product_view.xml',
        'wizard/sales_product_wizard_view.xml',
        'wizard/state_report_wizard_view.xml',
        'data/is_sale_sequence.xml',
        # 'wizard/sales_bouns_view.xml',
        'wizard/customer_report_wizard_view.xml',
        'wizard/product_state_wizard_view.xml',
        'wizard/best_partner_wizard_view.xml',
        'wizard/all_state_wizard_view.xml',
        'wizard/valuation_report_wizard_view.xml',
        'wizard/valuation_report_product_wizard_view.xml',
        'report/product_bouns.xml',
        'report/customer_report_view.xml',
        'report/product_state_report_view.xml',
        'report/state_report_view.xml',
        'report/best_partner_report_view.xml',
        'report/all_state_report_view.xml',
        'report/market_valuation_report_view.xml',
        'report/market_product_valuation_report_view.xml',
        'report/external_quation_invoice_tamplate_view.xml',

    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}

