{
    'name': 'Purchase',
    'version': '2.0',
    'author': 'Intellisoft',
    'website':'http://www.intellisoft.sd',
    'summary': 'Purchase Orders, Receipts, Vendor Bills',
    'sequence': 4,
    'category': 'Purchases',
    'description':"Manage goods requirement by Purchase Orders easily.",

    'depends': ['stock_landed_costs','is_custody_clearance_10','is_accounting_10','base'],
    'data': [
        'security/ir.model.access.csv',
        'views/is_purchases_view.xml',
        'views/is_customs_clearance.xml',
        'wizard/is_contract_vendor_report.xml',
        'wizard/is_contract_vendor_views.xml',
        'wizard/is_clearance_view.xml',
        'wizard/is_clearance_report.xml',
        # 'wizard/vendor_view.xml',
        'wizard/track_quantity_view.xml',
        'wizard/track_quantity_report.xml',
        'wizard/invoice_client_view.xml',
        'wizard/invoice_client_report.xml',
        'wizard/is_cultivate_form_view.xml',
        'wizard/is_cultivate_form_report.xml',
        'report/purchase_report.xml',
        # 'report/is_purchase_order_templates.xml',
        'data/is_purchase_sequence.xml',
    ],
    'application': True,
    'installable': True,
    'auto_install': False,
}

